# Generated by Django 4.2.8 on 2024-01-23 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_district_customuser_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(db_index=True, max_length=200)),
                ('ward', models.CharField(db_index=True, max_length=200)),
                ('street', models.CharField(db_index=True, max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
