# Generated by Django 4.2.8 on 2024-01-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookdoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdoctor',
            name='period',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
