# Generated by Django 4.2.8 on 2024-01-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookdoctor_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
