# Generated by Django 4.2.8 on 2024-01-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_purpose_purposetop_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='purposetop',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
