# Generated by Django 4.2.8 on 2024-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
