# Generated by Django 4.2.8 on 2024-01-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customuser_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sms_sent_payment',
            field=models.BooleanField(default=False),
        ),
    ]
