# Generated by Django 4.2.8 on 2024-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customuser_sms_sent_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('lipanamba', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=100)),
                ('notification', models.CharField(max_length=200)),
            ],
        ),
    ]
