# Generated by Django 4.2.8 on 2024-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orderconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirmation',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
