from django.urls import path
from . import views
from .views import ListThreads,CreateThread,ThreadView,CreateMessage,get_suggestions

urlpatterns = [
    path('home/', views.home,name='home'),
    path('base/', views.base,name='base'),
    path('base2/', views.base2,name='base2'),
    path('purpose/', views.purpose,name='purpose'),
    path('', views.index,name='index'),
    path('faqdelete/<int:id>/', views.faqdelete,name='faqdelete'),
    path('faqedit/<str:pk>/', views.faqedit,name='faqedit'),
    path('faqadd/', views.faqadd,name='faqadd'),
    path('news/', views.news,name='news'),
    path('newsedit/<str:pk>/', views.newsedit,name='newsedit'),
    path('newsdelete/<str:pk>/', views.newsdelete,name='newsdelete'),
    path('portfolioedit/<str:pk>/', views.portfolioedit,name='portfolioedit'),
    path('videoedit/<str:pk>/', views.videoedit,name='videoedit'),
    path('reviewadd/', views.reviewadd,name='reviewadd'),
    path('reviewedit/<str:pk>/', views.reviewedit,name='reviewedit'),
    path('reviewdelete/<str:pk>/', views.reviewdelete,name='reviewdelete'),
    path('serviceadd/', views.serviceadd,name='serviceadd'),
    path('serviceedit/<str:pk>/', views.serviceedit,name='serviceedit'),
    path('servicedelete/<str:pk>/', views.servicedelete,name='servicedelete'),
    path('whyuseagkiadd/', views.whyuseagkiadd,name='whyuseagkiadd'),
    path('whyuseagkiedit/<str:pk>/', views.whyuseagkiedit,name='whyuseagkiedit'),
    path('whyuseagkidelete/<str:pk>/', views.whyuseagkidelete,name='whyuseagkidelete'),
    path('frontPageedit/<str:pk>/', views.frontPageedit,name='frontPageedit'),


    path('registration/', views.registration,name='registration'),
    path('profile/', views.profile,name='profile'),
    path('signin/', views.signin,name='signin'),
    path('signout/', views.signout,name='signout'),
    path('sickinfo/', views.sickinfo,name='sickinfo'),
    path('sickinfolist/', views.sickinfolist,name='sickinfolist'),
    path('sickinfoDelete/<int:id>/', views.sickinfoDelete,name='sickinfoDelete'),
    path('sickinfolistprocesed/', views.sickinfolistprocesed,name='sickinfolistprocesed'),
    path('sickinfolistunprocesed/', views.sickinfolistunprocesed,name='sickinfolistunprocesed'),
    path('hospitalRegistration/', views.hospitalRegistration,name='hospitalRegistration'),
    path('registeredHosptal/', views.registeredHosptal,name='registeredHosptal'),
    path('contact_list/', views.contact_list,name='contact_list'),
    path('contactDelete/<int:id>/', views.contactDelete,name='contactDelete'),
    path('patient/', views.patient,name='patient'),
    path('patientList/', views.patientList,name='patientList'),
    path('patientDetail/<int:id>/', views.patientDetail,name='patientDetail'),
    path('patientDelete/<int:id>/', views.patientDelete,name='patientDelete'),
    path('reception/<int:id>/', views.reception,name='reception'),
    path('doctorFirstSession/<int:id>/', views.doctorFirstSession,name='doctorFirstSession'),
    path('doctorSecondSession/<int:id>/', views.doctorSecondSession,name='doctorSecondSession'),
    path('laboratory/<int:id>/', views.laboratory,name='laboratory'),
    path('pharmacy/<int:id>/', views.pharmacy,name='pharmacy'),
    path('userlist/', views.userlist,name='userlist'),
    path('userdelete/<int:id>/', views.userdelete,name='userdelete'),
    path('useredit/<int:id>/', views.useredit,name='useredit'),
    path('sickinfoEdit/<str:pk>/', views.sickinfoEdit,name='sickinfoEdit'),
    path('detailedUser/<int:id>/', views.detailedUser,name='detailedUser'),
    path('hospitalDelete/<int:id>/', views.hospitalDelete,name='hospitalDelete'),
    path('hospitalEdit/<int:id>/', views.hospitalEdit,name='hospitalEdit'),
    path('medicine/', views.medicine,name='medicine'),
    path('medicineAdd/', views.medicineAdd,name='medicineAdd'),
    path('medicineEdit/<int:id>/', views.medicineEdit,name='medicineEdit'),
    path('department/', views.department,name='department'),
    path('departmentAdd/', views.departmentAdd,name='departmentAdd'),
    path('departmentEdit/<int:id>/', views.departmentEdit,name='departmentEdit'),
    path('invoice/<int:id>/', views.invoice,name='invoice'),


    path('prescription_form/', views.prescription_form,name='prescription_form'),
    path('prescription_list/', views.prescription_list,name='prescription_list'),
    path('process_prescription/<int:patient_id>/', views.process_prescription, name='process_prescription'),
    path('edit_prescription/<int:prescription_id>/', views.edit_prescription, name='edit_prescription'),
    path('delete_prescription/<int:prescription_id>/', views.delete_prescription, name='delete_prescription'),
    path('patient_count_per_period/', views.patient_count_per_period, name='patient_count_per_period'),
    path('total_cost_per_period/', views.total_cost_per_period, name='total_cost_per_period'),

    path('inbox', ListThreads.as_view(),name='inbox'),
    path('create-thread',CreateThread.as_view(), name='create-thread'),
    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-messsage'),

    path('addCategory/', views.addCategory, name='addCategory'),
    path('editCategory/<int:id>/', views.editCategory, name='editCategory'),
    path('medicineCategory/', views.medicineCategory, name='medicineCategory'),
    path('medicationAdd/', views.medicationAdd, name='medicationAdd'),
    path('medicationList/', views.medicationList, name='medicationList'),
    path('medicationAllCart/', views.medicationAllCart, name='medicationAllCart'),
    path('medicationCartSingle/', views.medicationCartSingle, name='medicationCartSingle'),
    path('medicationListSingle/', views.medicationListSingle, name='medicationListSingle'),
    path('medicationRequest/', views.medicationRequest, name='medicationRequest'),
    path('medicationProcess/<int:id>/', views.medicationProcess, name='medicationProcess'),
    path('medicationDescription/<int:id>/', views.medicationDescription, name='medicationDescription'),
    path('medicationDescriptionStaff/<int:id>/', views.medicationDescriptionStaff, name='medicationDescriptionStaff'),
    path('medicationDescriptionEdit/<int:id>/', views.medicationDescriptionEdit, name='medicationDescriptionEdit'),

    path('bookLabTest/', views.bookLabTest, name='bookLabTest'),
    path('bookDoctor/', views.bookDoctor, name='bookDoctor'),
    path('doctorBookingAll/', views.doctorBookingAll, name='doctorBookingAll'),
    path('doctorBookingTime/<int:id>/', views.doctorBookingTime, name='doctorBookingTime'),
    path('doctorBookingDepartment/', views.doctorBookingDepartment, name='doctorBookingDepartment'),

    path('add_to_cart/<int:id>/', views.add_to_cart, name="add_to_cart"),
    path('order_summary/', views.OrderSummaryView.as_view(), name='order_summary'),
    path('remove_from_cart/<int:id>/', views.remove_from_cart, name="remove_from_cart"),
    path('remove_single_from_cart/<int:id>/', views.remove_single_from_cart, name="remove_single_from_cart"),

    path('api/suggestions/', get_suggestions, name='get_suggestions'),
   
   ]